apiVersion: v1
kind: Secret
metadata:
  name: apps-secrets
type: Opaque
stringData:
  POSTGRES_USER: "enter-username-here"
  POSTGRES_PASSWORD: "enter-password-here"
  POSTGRES_DB: "enter-database-name-here"
  DATABASE_URL: "enter-database-url-here"