apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgres.service.type | default "ClusterIP" }}
  selector:
    {{- include "platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.containerPort }}
      {{- if .Values.postgres.service.nodePort }}
      nodePort: {{ .Values.postgres.service.nodePort }}
      {{- end }}